#!/bin/bash

if [ "`ls -A /var/www/html`" = "" ]
then
	  mv /tmp/itop/web/* /var/www/html \
	  && rm -rf /tmp/itop
    echo "new itop installed."
else
    echo "Directory /var/www/html is not empty."
fi
